name: ci
on:
  push:
    branches:
      - master
      - dev
      - test

env:
  GO111MODULE: on
  GOPROXY: "https://proxy.golang.org"

jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    name: Run golangci-lint
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: go test -v -race -coverprofile="codecov.report" -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./codecov.report
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}